name: Publish .NET Core

on:
  workflow_dispatch:

env:
  DOTNET_VERSION: '10.x'

jobs:

  publish:
  
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Install depeíííndencies
      run: dotnet restore
      
    - name: Build
      run: |
        cd mmm
        dotnet publish -c Release -o ../publish/linux-x64 -r linux-x64 /p:UseAppHost=true
        dotnet publish -c Release -o ../publish/win-x64 -r win-x64 /p:UseAppHost=true
        mv ../publish/linux-x64/mmm ../publish/linux-x64/mmm-linux-x64
        mv ../publish/win-x64/mmm ../publish/win-x64/mmm-win-x64

    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
        
    - name: Create tag
      uses: EndBug/latest-tag@latest
      with:
        ref: ${{ steps.date.outputs.date }}
        description: :3

    - name: Publish Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ./publish/linux-x64/mmm-linux-x64
          ./publish/win-x64/mmm-win-x64
        tag_name: ${{ steps.date.outputs.date }}
        name: Release ${{ steps.date.outputs.date }}
        fail_on_unmatched_files: true
